/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as PortfolioJudgeRouteImport } from './routes/portfolio-judge'
import { Route as LinkedinOptimizerRouteImport } from './routes/linkedin-optimizer'
import { Route as JdMatcherRouteImport } from './routes/jd-matcher'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as CoverLetterRouteImport } from './routes/cover-letter'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysisOverviewRouteImport } from './routes/analysis.overview'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioJudgeRoute = PortfolioJudgeRouteImport.update({
  id: '/portfolio-judge',
  path: '/portfolio-judge',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedinOptimizerRoute = LinkedinOptimizerRouteImport.update({
  id: '/linkedin-optimizer',
  path: '/linkedin-optimizer',
  getParentRoute: () => rootRouteImport,
} as any)
const JdMatcherRoute = JdMatcherRouteImport.update({
  id: '/jd-matcher',
  path: '/jd-matcher',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverLetterRoute = CoverLetterRouteImport.update({
  id: '/cover-letter',
  path: '/cover-letter',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisOverviewRoute = AnalysisOverviewRouteImport.update({
  id: '/analysis/overview',
  path: '/analysis/overview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cover-letter': typeof CoverLetterRoute
  '/interview': typeof InterviewRoute
  '/jd-matcher': typeof JdMatcherRoute
  '/linkedin-optimizer': typeof LinkedinOptimizerRoute
  '/portfolio-judge': typeof PortfolioJudgeRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/analysis/overview': typeof AnalysisOverviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cover-letter': typeof CoverLetterRoute
  '/interview': typeof InterviewRoute
  '/jd-matcher': typeof JdMatcherRoute
  '/linkedin-optimizer': typeof LinkedinOptimizerRoute
  '/portfolio-judge': typeof PortfolioJudgeRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/analysis/overview': typeof AnalysisOverviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cover-letter': typeof CoverLetterRoute
  '/interview': typeof InterviewRoute
  '/jd-matcher': typeof JdMatcherRoute
  '/linkedin-optimizer': typeof LinkedinOptimizerRoute
  '/portfolio-judge': typeof PortfolioJudgeRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/analysis/overview': typeof AnalysisOverviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cover-letter'
    | '/interview'
    | '/jd-matcher'
    | '/linkedin-optimizer'
    | '/portfolio-judge'
    | '/roadmap'
    | '/settings'
    | '/analysis/overview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cover-letter'
    | '/interview'
    | '/jd-matcher'
    | '/linkedin-optimizer'
    | '/portfolio-judge'
    | '/roadmap'
    | '/settings'
    | '/analysis/overview'
  id:
    | '__root__'
    | '/'
    | '/cover-letter'
    | '/interview'
    | '/jd-matcher'
    | '/linkedin-optimizer'
    | '/portfolio-judge'
    | '/roadmap'
    | '/settings'
    | '/analysis/overview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoverLetterRoute: typeof CoverLetterRoute
  InterviewRoute: typeof InterviewRoute
  JdMatcherRoute: typeof JdMatcherRoute
  LinkedinOptimizerRoute: typeof LinkedinOptimizerRoute
  PortfolioJudgeRoute: typeof PortfolioJudgeRoute
  RoadmapRoute: typeof RoadmapRoute
  SettingsRoute: typeof SettingsRoute
  AnalysisOverviewRoute: typeof AnalysisOverviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio-judge': {
      id: '/portfolio-judge'
      path: '/portfolio-judge'
      fullPath: '/portfolio-judge'
      preLoaderRoute: typeof PortfolioJudgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkedin-optimizer': {
      id: '/linkedin-optimizer'
      path: '/linkedin-optimizer'
      fullPath: '/linkedin-optimizer'
      preLoaderRoute: typeof LinkedinOptimizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jd-matcher': {
      id: '/jd-matcher'
      path: '/jd-matcher'
      fullPath: '/jd-matcher'
      preLoaderRoute: typeof JdMatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cover-letter': {
      id: '/cover-letter'
      path: '/cover-letter'
      fullPath: '/cover-letter'
      preLoaderRoute: typeof CoverLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/overview': {
      id: '/analysis/overview'
      path: '/analysis/overview'
      fullPath: '/analysis/overview'
      preLoaderRoute: typeof AnalysisOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoverLetterRoute: CoverLetterRoute,
  InterviewRoute: InterviewRoute,
  JdMatcherRoute: JdMatcherRoute,
  LinkedinOptimizerRoute: LinkedinOptimizerRoute,
  PortfolioJudgeRoute: PortfolioJudgeRoute,
  RoadmapRoute: RoadmapRoute,
  SettingsRoute: SettingsRoute,
  AnalysisOverviewRoute: AnalysisOverviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
